export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_AMOUNT = 'SET_AMOUNT';

export const GET_CURRENCIES_RATES_REQUEST = 'GET_CURRENCIES_RATES_REQUEST';
export const GET_CURRENCIES_RATES_SUCCESS = 'GET_CURRENCIES_RATES_SUCCESS';
export const GET_CURRENCIES_RATES_FAILURE = 'GET_CURRENCIES_RATES_FAILURE';

export const INIT_CURRENCIES_REQUEST = 'INIT_CURRENCIES_REQUEST';
export const INIT_CURRENCIES_SUCCESS = 'INIT_CURRENCIES_SUCCESS';
export const INIT_CURRENCIES_FAILURE = 'INIT_CURRENCIES_FAILURE';
